minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
fabric_version=0.141.3+1.21.11
modmenu_version=17.0.0-beta.2
owo_version=0.13.0+1.21.11

# owo-lib runtime deps
endec_version=0.1.12
endec_netty_version=0.1.6
endec_gson_version=0.1.7
endec_jankson_version=0.1.7

voicechat_api_version=2.6.0
voicechat_version=1.21.11-2.6.12
